---
micronaut:
  application:
    name: mn-gorm-flyway-reproducer

---
jpa:
  properties:
    hbm2ddl:
      auto: none
    show_sql: true

dataSource:
#  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  dbCreate: none
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db
